#!/bin/bash
ip=$1
nmap --script targets-asn --script-args targets-asn.asn=$1 -vv | tee -a asn_ip

#nmap --script targets-asn --script-args targets-asn.asn=14061
#cat asn_ip|tr -d '| _'|grep -E '([0-9]{1,3}\.)[0-9]{1,3}/'
